// Code generated by protoc-gen-go-webitel. DO NOT EDIT.
// versions:
// - protoc-gen-go-webitel v1.0.0
// - protoc                (unknown)

package email

// WebitelServicesInfo is the list of services defined in proto files.
type WebitelServicesInfo map[string]WebitelServices

type WebitelServices struct {
	ObjClass           string
	AdditionalLicenses []string
	WebitelMethods     map[string]WebitelMethod
}

// WebitelMethod is the list of methods defined in this service.
type WebitelMethod struct {
	HttpBindings []*HttpBinding
	Access       int
	Input        string
	Output       string
}

type HttpBinding struct {
	Path   string
	Method string
}

var WebitelAPI = WebitelServicesInfo{
	"EmailProfiles": WebitelServices{
		ObjClass:           "email_profile",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListEmailProfiles": WebitelMethod{
				Access: 1,
				Input:  "ListEmailProfilesRequest",
				Output: "EmailProfileList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/email/profiles",
						Method: "GET",
					},
				},
			},
			"LocateEmailProfile": WebitelMethod{
				Access: 1,
				Input:  "LocateEmailProfileRequest",
				Output: "EmailProfile",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/email/profiles/{id}",
						Method: "GET",
					},
				},
			},
			"CreateEmailProfile": WebitelMethod{
				Access: 0,
				Input:  "CreateEmailProfileRequest",
				Output: "EmailProfile",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/email/profiles",
						Method: "POST",
					},
				},
			},
			"UpdateEmailProfile": WebitelMethod{
				Access: 2,
				Input:  "UpdateEmailProfileRequest",
				Output: "EmailProfile",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/email/profiles/{id}",
						Method: "PUT",
					},
					{
						Path:   "/v1/email/profiles/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteEmailProfile": WebitelMethod{
				Access: 3,
				Input:  "DeleteEmailProfileRequest",
				Output: "EmailProfile",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/email/profiles/{id}",
						Method: "DELETE",
					},
				},
			},
			"TestEmailProfile": WebitelMethod{
				Access: 2,
				Input:  "TestEmailProfileRequest",
				Output: "TestEmailProfileResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/email/profiles/{id}/test",
						Method: "POST",
					},
				},
			},
			"BeginEmailProfileOAuth": WebitelMethod{
				Access: 2,
				Input:  "BeginEmailProfileOAuthRequest",
				Output: "BeginEmailProfileOAuthResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/email/profiles/{id}/oauth/start",
						Method: "POST",
					},
				},
			},
			"CompleteEmailProfileOAuth": WebitelMethod{
				Access: 2,
				Input:  "CompleteEmailProfileOAuthRequest",
				Output: "EmailProfile",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/email/profiles/{id}/oauth/callback",
						Method: "POST",
					},
				},
			},
			"DisconnectEmailProfileOAuth": WebitelMethod{
				Access: 2,
				Input:  "DisconnectEmailProfileOAuthRequest",
				Output: "EmailProfile",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/email/profiles/{id}/oauth",
						Method: "DELETE",
					},
				},
			},
		},
	},
}
