// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: profile.proto

package email

import (
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailAuthType int32

const (
	EmailAuthType_EMAIL_AUTH_TYPE_UNSPECIFIED EmailAuthType = 0
	EmailAuthType_EMAIL_AUTH_TYPE_BASIC       EmailAuthType = 1
	EmailAuthType_EMAIL_AUTH_TYPE_OAUTH2      EmailAuthType = 2
)

// Enum value maps for EmailAuthType.
var (
	EmailAuthType_name = map[int32]string{
		0: "EMAIL_AUTH_TYPE_UNSPECIFIED",
		1: "EMAIL_AUTH_TYPE_BASIC",
		2: "EMAIL_AUTH_TYPE_OAUTH2",
	}
	EmailAuthType_value = map[string]int32{
		"EMAIL_AUTH_TYPE_UNSPECIFIED": 0,
		"EMAIL_AUTH_TYPE_BASIC":       1,
		"EMAIL_AUTH_TYPE_OAUTH2":      2,
	}
)

func (x EmailAuthType) Enum() *EmailAuthType {
	p := new(EmailAuthType)
	*p = x
	return p
}

func (x EmailAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_proto_enumTypes[0].Descriptor()
}

func (EmailAuthType) Type() protoreflect.EnumType {
	return &file_profile_proto_enumTypes[0]
}

func (x EmailAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailAuthType.Descriptor instead.
func (EmailAuthType) EnumDescriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

type EmailOAuthProvider int32

const (
	EmailOAuthProvider_EMAIL_OAUTH_PROVIDER_UNSPECIFIED EmailOAuthProvider = 0
	EmailOAuthProvider_EMAIL_OAUTH_PROVIDER_GOOGLE      EmailOAuthProvider = 1
	EmailOAuthProvider_EMAIL_OAUTH_PROVIDER_MICROSOFT   EmailOAuthProvider = 2
)

// Enum value maps for EmailOAuthProvider.
var (
	EmailOAuthProvider_name = map[int32]string{
		0: "EMAIL_OAUTH_PROVIDER_UNSPECIFIED",
		1: "EMAIL_OAUTH_PROVIDER_GOOGLE",
		2: "EMAIL_OAUTH_PROVIDER_MICROSOFT",
	}
	EmailOAuthProvider_value = map[string]int32{
		"EMAIL_OAUTH_PROVIDER_UNSPECIFIED": 0,
		"EMAIL_OAUTH_PROVIDER_GOOGLE":      1,
		"EMAIL_OAUTH_PROVIDER_MICROSOFT":   2,
	}
)

func (x EmailOAuthProvider) Enum() *EmailOAuthProvider {
	p := new(EmailOAuthProvider)
	*p = x
	return p
}

func (x EmailOAuthProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailOAuthProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_proto_enumTypes[1].Descriptor()
}

func (EmailOAuthProvider) Type() protoreflect.EnumType {
	return &file_profile_proto_enumTypes[1]
}

func (x EmailOAuthProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailOAuthProvider.Descriptor instead.
func (EmailOAuthProvider) EnumDescriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

type EmailConnectionSecurity int32

const (
	EmailConnectionSecurity_EMAIL_CONNECTION_SECURITY_UNSPECIFIED EmailConnectionSecurity = 0
	EmailConnectionSecurity_EMAIL_CONNECTION_SECURITY_TLS         EmailConnectionSecurity = 1
	EmailConnectionSecurity_EMAIL_CONNECTION_SECURITY_STARTTLS    EmailConnectionSecurity = 2
)

// Enum value maps for EmailConnectionSecurity.
var (
	EmailConnectionSecurity_name = map[int32]string{
		0: "EMAIL_CONNECTION_SECURITY_UNSPECIFIED",
		1: "EMAIL_CONNECTION_SECURITY_TLS",
		2: "EMAIL_CONNECTION_SECURITY_STARTTLS",
	}
	EmailConnectionSecurity_value = map[string]int32{
		"EMAIL_CONNECTION_SECURITY_UNSPECIFIED": 0,
		"EMAIL_CONNECTION_SECURITY_TLS":         1,
		"EMAIL_CONNECTION_SECURITY_STARTTLS":    2,
	}
)

func (x EmailConnectionSecurity) Enum() *EmailConnectionSecurity {
	p := new(EmailConnectionSecurity)
	*p = x
	return p
}

func (x EmailConnectionSecurity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailConnectionSecurity) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_proto_enumTypes[2].Descriptor()
}

func (EmailConnectionSecurity) Type() protoreflect.EnumType {
	return &file_profile_proto_enumTypes[2]
}

func (x EmailConnectionSecurity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailConnectionSecurity.Descriptor instead.
func (EmailConnectionSecurity) EnumDescriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

type EmailConnectionState int32

const (
	EmailConnectionState_EMAIL_CONNECTION_STATE_UNSPECIFIED              EmailConnectionState = 0
	EmailConnectionState_EMAIL_CONNECTION_STATE_IDLE                     EmailConnectionState = 1
	EmailConnectionState_EMAIL_CONNECTION_STATE_READY                    EmailConnectionState = 2
	EmailConnectionState_EMAIL_CONNECTION_STATE_ERROR                    EmailConnectionState = 3
	EmailConnectionState_EMAIL_CONNECTION_STATE_REAUTHORIZATION_REQUIRED EmailConnectionState = 4
)

// Enum value maps for EmailConnectionState.
var (
	EmailConnectionState_name = map[int32]string{
		0: "EMAIL_CONNECTION_STATE_UNSPECIFIED",
		1: "EMAIL_CONNECTION_STATE_IDLE",
		2: "EMAIL_CONNECTION_STATE_READY",
		3: "EMAIL_CONNECTION_STATE_ERROR",
		4: "EMAIL_CONNECTION_STATE_REAUTHORIZATION_REQUIRED",
	}
	EmailConnectionState_value = map[string]int32{
		"EMAIL_CONNECTION_STATE_UNSPECIFIED":              0,
		"EMAIL_CONNECTION_STATE_IDLE":                     1,
		"EMAIL_CONNECTION_STATE_READY":                    2,
		"EMAIL_CONNECTION_STATE_ERROR":                    3,
		"EMAIL_CONNECTION_STATE_REAUTHORIZATION_REQUIRED": 4,
	}
)

func (x EmailConnectionState) Enum() *EmailConnectionState {
	p := new(EmailConnectionState)
	*p = x
	return p
}

func (x EmailConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_proto_enumTypes[3].Descriptor()
}

func (EmailConnectionState) Type() protoreflect.EnumType {
	return &file_profile_proto_enumTypes[3]
}

func (x EmailConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailConnectionState.Descriptor instead.
func (EmailConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{3}
}

// EmailProfile is a mailbox configuration returned by the API.
// Credentials and OAuth tokens are intentionally omitted.
type EmailProfile struct {
	state                      protoimpl.MessageState  `protogen:"open.v1"`
	Id                         int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId                   int64                   `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Name                       string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description                string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Enabled                    bool                    `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	EmailAddress               string                  `protobuf:"bytes,6,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	SenderName                 string                  `protobuf:"bytes,7,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	ReplyTo                    string                  `protobuf:"bytes,8,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Signature                  string                  `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	ImapHost                   string                  `protobuf:"bytes,10,opt,name=imap_host,json=imapHost,proto3" json:"imap_host,omitempty"`
	ImapPort                   int32                   `protobuf:"varint,11,opt,name=imap_port,json=imapPort,proto3" json:"imap_port,omitempty"`
	ImapSecurity               EmailConnectionSecurity `protobuf:"varint,12,opt,name=imap_security,json=imapSecurity,proto3,enum=webitel.email.EmailConnectionSecurity" json:"imap_security,omitempty"`
	SmtpHost                   string                  `protobuf:"bytes,13,opt,name=smtp_host,json=smtpHost,proto3" json:"smtp_host,omitempty"`
	SmtpPort                   int32                   `protobuf:"varint,14,opt,name=smtp_port,json=smtpPort,proto3" json:"smtp_port,omitempty"`
	SmtpSecurity               EmailConnectionSecurity `protobuf:"varint,15,opt,name=smtp_security,json=smtpSecurity,proto3,enum=webitel.email.EmailConnectionSecurity" json:"smtp_security,omitempty"`
	Username                   string                  `protobuf:"bytes,16,opt,name=username,proto3" json:"username,omitempty"`
	Mailbox                    string                  `protobuf:"bytes,17,opt,name=mailbox,proto3" json:"mailbox,omitempty"`
	FetchIntervalSeconds       int32                   `protobuf:"varint,18,opt,name=fetch_interval_seconds,json=fetchIntervalSeconds,proto3" json:"fetch_interval_seconds,omitempty"`
	FlowId                     int64                   `protobuf:"varint,19,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	AuthType                   EmailAuthType           `protobuf:"varint,20,opt,name=auth_type,json=authType,proto3,enum=webitel.email.EmailAuthType" json:"auth_type,omitempty"`
	OauthProvider              EmailOAuthProvider      `protobuf:"varint,21,opt,name=oauth_provider,json=oauthProvider,proto3,enum=webitel.email.EmailOAuthProvider" json:"oauth_provider,omitempty"`
	OauthClientId              string                  `protobuf:"bytes,22,opt,name=oauth_client_id,json=oauthClientId,proto3" json:"oauth_client_id,omitempty"`
	OauthConnected             bool                    `protobuf:"varint,23,opt,name=oauth_connected,json=oauthConnected,proto3" json:"oauth_connected,omitempty"`
	ConnectionState            EmailConnectionState    `protobuf:"varint,24,opt,name=connection_state,json=connectionState,proto3,enum=webitel.email.EmailConnectionState" json:"connection_state,omitempty"`
	LastSuccessfulConnectionAt int64                   `protobuf:"varint,25,opt,name=last_successful_connection_at,json=lastSuccessfulConnectionAt,proto3" json:"last_successful_connection_at,omitempty"`
	ConnectionError            string                  `protobuf:"bytes,26,opt,name=connection_error,json=connectionError,proto3" json:"connection_error,omitempty"`
	CreatedAt                  int64                   `protobuf:"varint,30,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy                  *Lookup                 `protobuf:"bytes,31,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt                  int64                   `protobuf:"varint,32,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy                  *Lookup                 `protobuf:"bytes,33,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *EmailProfile) Reset() {
	*x = EmailProfile{}
	mi := &file_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailProfile) ProtoMessage() {}

func (x *EmailProfile) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailProfile.ProtoReflect.Descriptor instead.
func (*EmailProfile) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

func (x *EmailProfile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmailProfile) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *EmailProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmailProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EmailProfile) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EmailProfile) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *EmailProfile) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *EmailProfile) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *EmailProfile) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *EmailProfile) GetImapHost() string {
	if x != nil {
		return x.ImapHost
	}
	return ""
}

func (x *EmailProfile) GetImapPort() int32 {
	if x != nil {
		return x.ImapPort
	}
	return 0
}

func (x *EmailProfile) GetImapSecurity() EmailConnectionSecurity {
	if x != nil {
		return x.ImapSecurity
	}
	return EmailConnectionSecurity_EMAIL_CONNECTION_SECURITY_UNSPECIFIED
}

func (x *EmailProfile) GetSmtpHost() string {
	if x != nil {
		return x.SmtpHost
	}
	return ""
}

func (x *EmailProfile) GetSmtpPort() int32 {
	if x != nil {
		return x.SmtpPort
	}
	return 0
}

func (x *EmailProfile) GetSmtpSecurity() EmailConnectionSecurity {
	if x != nil {
		return x.SmtpSecurity
	}
	return EmailConnectionSecurity_EMAIL_CONNECTION_SECURITY_UNSPECIFIED
}

func (x *EmailProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EmailProfile) GetMailbox() string {
	if x != nil {
		return x.Mailbox
	}
	return ""
}

func (x *EmailProfile) GetFetchIntervalSeconds() int32 {
	if x != nil {
		return x.FetchIntervalSeconds
	}
	return 0
}

func (x *EmailProfile) GetFlowId() int64 {
	if x != nil {
		return x.FlowId
	}
	return 0
}

func (x *EmailProfile) GetAuthType() EmailAuthType {
	if x != nil {
		return x.AuthType
	}
	return EmailAuthType_EMAIL_AUTH_TYPE_UNSPECIFIED
}

func (x *EmailProfile) GetOauthProvider() EmailOAuthProvider {
	if x != nil {
		return x.OauthProvider
	}
	return EmailOAuthProvider_EMAIL_OAUTH_PROVIDER_UNSPECIFIED
}

func (x *EmailProfile) GetOauthClientId() string {
	if x != nil {
		return x.OauthClientId
	}
	return ""
}

func (x *EmailProfile) GetOauthConnected() bool {
	if x != nil {
		return x.OauthConnected
	}
	return false
}

func (x *EmailProfile) GetConnectionState() EmailConnectionState {
	if x != nil {
		return x.ConnectionState
	}
	return EmailConnectionState_EMAIL_CONNECTION_STATE_UNSPECIFIED
}

func (x *EmailProfile) GetLastSuccessfulConnectionAt() int64 {
	if x != nil {
		return x.LastSuccessfulConnectionAt
	}
	return 0
}

func (x *EmailProfile) GetConnectionError() string {
	if x != nil {
		return x.ConnectionError
	}
	return ""
}

func (x *EmailProfile) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *EmailProfile) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *EmailProfile) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *EmailProfile) GetUpdatedBy() *Lookup {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

// InputEmailProfile contains fields accepted when a profile is created or
// updated. Password and OAuth client secret are write-only API fields.
type InputEmailProfile struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	Name                 string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Enabled              bool                    `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	EmailAddress         string                  `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	SenderName           string                  `protobuf:"bytes,5,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	ReplyTo              string                  `protobuf:"bytes,6,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Signature            string                  `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	ImapHost             string                  `protobuf:"bytes,8,opt,name=imap_host,json=imapHost,proto3" json:"imap_host,omitempty"`
	ImapPort             int32                   `protobuf:"varint,9,opt,name=imap_port,json=imapPort,proto3" json:"imap_port,omitempty"`
	ImapSecurity         EmailConnectionSecurity `protobuf:"varint,10,opt,name=imap_security,json=imapSecurity,proto3,enum=webitel.email.EmailConnectionSecurity" json:"imap_security,omitempty"`
	SmtpHost             string                  `protobuf:"bytes,11,opt,name=smtp_host,json=smtpHost,proto3" json:"smtp_host,omitempty"`
	SmtpPort             int32                   `protobuf:"varint,12,opt,name=smtp_port,json=smtpPort,proto3" json:"smtp_port,omitempty"`
	SmtpSecurity         EmailConnectionSecurity `protobuf:"varint,13,opt,name=smtp_security,json=smtpSecurity,proto3,enum=webitel.email.EmailConnectionSecurity" json:"smtp_security,omitempty"`
	Username             string                  `protobuf:"bytes,14,opt,name=username,proto3" json:"username,omitempty"`
	Password             string                  `protobuf:"bytes,15,opt,name=password,proto3" json:"password,omitempty"`
	Mailbox              string                  `protobuf:"bytes,16,opt,name=mailbox,proto3" json:"mailbox,omitempty"`
	FetchIntervalSeconds int32                   `protobuf:"varint,17,opt,name=fetch_interval_seconds,json=fetchIntervalSeconds,proto3" json:"fetch_interval_seconds,omitempty"`
	FlowId               int64                   `protobuf:"varint,18,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	AuthType             EmailAuthType           `protobuf:"varint,19,opt,name=auth_type,json=authType,proto3,enum=webitel.email.EmailAuthType" json:"auth_type,omitempty"`
	OauthProvider        EmailOAuthProvider      `protobuf:"varint,20,opt,name=oauth_provider,json=oauthProvider,proto3,enum=webitel.email.EmailOAuthProvider" json:"oauth_provider,omitempty"`
	OauthClientId        string                  `protobuf:"bytes,21,opt,name=oauth_client_id,json=oauthClientId,proto3" json:"oauth_client_id,omitempty"`
	OauthClientSecret    string                  `protobuf:"bytes,22,opt,name=oauth_client_secret,json=oauthClientSecret,proto3" json:"oauth_client_secret,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InputEmailProfile) Reset() {
	*x = InputEmailProfile{}
	mi := &file_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputEmailProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputEmailProfile) ProtoMessage() {}

func (x *InputEmailProfile) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputEmailProfile.ProtoReflect.Descriptor instead.
func (*InputEmailProfile) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

func (x *InputEmailProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputEmailProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InputEmailProfile) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *InputEmailProfile) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *InputEmailProfile) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *InputEmailProfile) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *InputEmailProfile) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *InputEmailProfile) GetImapHost() string {
	if x != nil {
		return x.ImapHost
	}
	return ""
}

func (x *InputEmailProfile) GetImapPort() int32 {
	if x != nil {
		return x.ImapPort
	}
	return 0
}

func (x *InputEmailProfile) GetImapSecurity() EmailConnectionSecurity {
	if x != nil {
		return x.ImapSecurity
	}
	return EmailConnectionSecurity_EMAIL_CONNECTION_SECURITY_UNSPECIFIED
}

func (x *InputEmailProfile) GetSmtpHost() string {
	if x != nil {
		return x.SmtpHost
	}
	return ""
}

func (x *InputEmailProfile) GetSmtpPort() int32 {
	if x != nil {
		return x.SmtpPort
	}
	return 0
}

func (x *InputEmailProfile) GetSmtpSecurity() EmailConnectionSecurity {
	if x != nil {
		return x.SmtpSecurity
	}
	return EmailConnectionSecurity_EMAIL_CONNECTION_SECURITY_UNSPECIFIED
}

func (x *InputEmailProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *InputEmailProfile) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *InputEmailProfile) GetMailbox() string {
	if x != nil {
		return x.Mailbox
	}
	return ""
}

func (x *InputEmailProfile) GetFetchIntervalSeconds() int32 {
	if x != nil {
		return x.FetchIntervalSeconds
	}
	return 0
}

func (x *InputEmailProfile) GetFlowId() int64 {
	if x != nil {
		return x.FlowId
	}
	return 0
}

func (x *InputEmailProfile) GetAuthType() EmailAuthType {
	if x != nil {
		return x.AuthType
	}
	return EmailAuthType_EMAIL_AUTH_TYPE_UNSPECIFIED
}

func (x *InputEmailProfile) GetOauthProvider() EmailOAuthProvider {
	if x != nil {
		return x.OauthProvider
	}
	return EmailOAuthProvider_EMAIL_OAUTH_PROVIDER_UNSPECIFIED
}

func (x *InputEmailProfile) GetOauthClientId() string {
	if x != nil {
		return x.OauthClientId
	}
	return ""
}

func (x *InputEmailProfile) GetOauthClientSecret() string {
	if x != nil {
		return x.OauthClientSecret
	}
	return ""
}

// ListEmailProfilesRequest defines pagination, search, sorting, and field
// selection for Email Profiles.
type ListEmailProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q             string                 `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Fields        []string               `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailProfilesRequest) Reset() {
	*x = ListEmailProfilesRequest{}
	mi := &file_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailProfilesRequest) ProtoMessage() {}

func (x *ListEmailProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListEmailProfilesRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

func (x *ListEmailProfilesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEmailProfilesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListEmailProfilesRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListEmailProfilesRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListEmailProfilesRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// EmailProfileList is a page of Email Profiles.
type EmailProfileList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EmailProfile        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Next          bool                   `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailProfileList) Reset() {
	*x = EmailProfileList{}
	mi := &file_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailProfileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailProfileList) ProtoMessage() {}

func (x *EmailProfileList) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailProfileList.ProtoReflect.Descriptor instead.
func (*EmailProfileList) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{3}
}

func (x *EmailProfileList) GetItems() []*EmailProfile {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *EmailProfileList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

// LocateEmailProfileRequest selects an Email Profile by id.
type LocateEmailProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateEmailProfileRequest) Reset() {
	*x = LocateEmailProfileRequest{}
	mi := &file_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateEmailProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateEmailProfileRequest) ProtoMessage() {}

func (x *LocateEmailProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateEmailProfileRequest.ProtoReflect.Descriptor instead.
func (*LocateEmailProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{4}
}

func (x *LocateEmailProfileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// CreateEmailProfileRequest wraps the Email Profile fields to create.
type CreateEmailProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *InputEmailProfile     `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailProfileRequest) Reset() {
	*x = CreateEmailProfileRequest{}
	mi := &file_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailProfileRequest) ProtoMessage() {}

func (x *CreateEmailProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateEmailProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEmailProfileRequest) GetInput() *InputEmailProfile {
	if x != nil {
		return x.Input
	}
	return nil
}

// UpdateEmailProfileRequest wraps the Email Profile id and updated fields.
type UpdateEmailProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Input         *InputEmailProfile     `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailProfileRequest) Reset() {
	*x = UpdateEmailProfileRequest{}
	mi := &file_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailProfileRequest) ProtoMessage() {}

func (x *UpdateEmailProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEmailProfileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEmailProfileRequest) GetInput() *InputEmailProfile {
	if x != nil {
		return x.Input
	}
	return nil
}

// DeleteEmailProfileRequest selects an Email Profile by id.
type DeleteEmailProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmailProfileRequest) Reset() {
	*x = DeleteEmailProfileRequest{}
	mi := &file_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmailProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailProfileRequest) ProtoMessage() {}

func (x *DeleteEmailProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmailProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEmailProfileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TestEmailProfileRequest selects a saved Email Profile to test.
type TestEmailProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestEmailProfileRequest) Reset() {
	*x = TestEmailProfileRequest{}
	mi := &file_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestEmailProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestEmailProfileRequest) ProtoMessage() {}

func (x *TestEmailProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestEmailProfileRequest.ProtoReflect.Descriptor instead.
func (*TestEmailProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{8}
}

func (x *TestEmailProfileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// EmailConnectionTestResult describes a single protocol connection test.
type EmailConnectionTestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailConnectionTestResult) Reset() {
	*x = EmailConnectionTestResult{}
	mi := &file_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailConnectionTestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailConnectionTestResult) ProtoMessage() {}

func (x *EmailConnectionTestResult) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailConnectionTestResult.ProtoReflect.Descriptor instead.
func (*EmailConnectionTestResult) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{9}
}

func (x *EmailConnectionTestResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmailConnectionTestResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TestEmailProfileResponse contains independent IMAP and SMTP test results.
type TestEmailProfileResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Imap          *EmailConnectionTestResult `protobuf:"bytes,1,opt,name=imap,proto3" json:"imap,omitempty"`
	Smtp          *EmailConnectionTestResult `protobuf:"bytes,2,opt,name=smtp,proto3" json:"smtp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestEmailProfileResponse) Reset() {
	*x = TestEmailProfileResponse{}
	mi := &file_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestEmailProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestEmailProfileResponse) ProtoMessage() {}

func (x *TestEmailProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestEmailProfileResponse.ProtoReflect.Descriptor instead.
func (*TestEmailProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{10}
}

func (x *TestEmailProfileResponse) GetImap() *EmailConnectionTestResult {
	if x != nil {
		return x.Imap
	}
	return nil
}

func (x *TestEmailProfileResponse) GetSmtp() *EmailConnectionTestResult {
	if x != nil {
		return x.Smtp
	}
	return nil
}

// BeginEmailProfileOAuthRequest selects an Email Profile for OAuth
// authorization.
type BeginEmailProfileOAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginEmailProfileOAuthRequest) Reset() {
	*x = BeginEmailProfileOAuthRequest{}
	mi := &file_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginEmailProfileOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginEmailProfileOAuthRequest) ProtoMessage() {}

func (x *BeginEmailProfileOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginEmailProfileOAuthRequest.ProtoReflect.Descriptor instead.
func (*BeginEmailProfileOAuthRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{11}
}

func (x *BeginEmailProfileOAuthRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// BeginEmailProfileOAuthResponse provides the OAuth authorization entry point.
type BeginEmailProfileOAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginEmailProfileOAuthResponse) Reset() {
	*x = BeginEmailProfileOAuthResponse{}
	mi := &file_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginEmailProfileOAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginEmailProfileOAuthResponse) ProtoMessage() {}

func (x *BeginEmailProfileOAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginEmailProfileOAuthResponse.ProtoReflect.Descriptor instead.
func (*BeginEmailProfileOAuthResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{12}
}

func (x *BeginEmailProfileOAuthResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *BeginEmailProfileOAuthResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// CompleteEmailProfileOAuthRequest contains the authorization code returned by
// the OAuth provider and the state generated when authorization began.
type CompleteEmailProfileOAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteEmailProfileOAuthRequest) Reset() {
	*x = CompleteEmailProfileOAuthRequest{}
	mi := &file_profile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteEmailProfileOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteEmailProfileOAuthRequest) ProtoMessage() {}

func (x *CompleteEmailProfileOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteEmailProfileOAuthRequest.ProtoReflect.Descriptor instead.
func (*CompleteEmailProfileOAuthRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteEmailProfileOAuthRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompleteEmailProfileOAuthRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteEmailProfileOAuthRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// DisconnectEmailProfileOAuthRequest selects an Email Profile whose OAuth
// authorization should be removed.
type DisconnectEmailProfileOAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectEmailProfileOAuthRequest) Reset() {
	*x = DisconnectEmailProfileOAuthRequest{}
	mi := &file_profile_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectEmailProfileOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectEmailProfileOAuthRequest) ProtoMessage() {}

func (x *DisconnectEmailProfileOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectEmailProfileOAuthRequest.ProtoReflect.Descriptor instead.
func (*DisconnectEmailProfileOAuthRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{14}
}

func (x *DisconnectEmailProfileOAuthRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_profile_proto protoreflect.FileDescriptor

const file_profile_proto_rawDesc = "" +
	"\n" +
	"\rprofile.proto\x12\rwebitel.email\x1a\rgeneral.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1aproto/webitel/option.proto\"\xcf\t\n" +
	"\fEmailProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12#\n" +
	"\remail_address\x18\x06 \x01(\tR\femailAddress\x12\x1f\n" +
	"\vsender_name\x18\a \x01(\tR\n" +
	"senderName\x12\x19\n" +
	"\breply_to\x18\b \x01(\tR\areplyTo\x12\x1c\n" +
	"\tsignature\x18\t \x01(\tR\tsignature\x12\x1b\n" +
	"\timap_host\x18\n" +
	" \x01(\tR\bimapHost\x12\x1b\n" +
	"\timap_port\x18\v \x01(\x05R\bimapPort\x12K\n" +
	"\rimap_security\x18\f \x01(\x0e2&.webitel.email.EmailConnectionSecurityR\fimapSecurity\x12\x1b\n" +
	"\tsmtp_host\x18\r \x01(\tR\bsmtpHost\x12\x1b\n" +
	"\tsmtp_port\x18\x0e \x01(\x05R\bsmtpPort\x12K\n" +
	"\rsmtp_security\x18\x0f \x01(\x0e2&.webitel.email.EmailConnectionSecurityR\fsmtpSecurity\x12\x1a\n" +
	"\busername\x18\x10 \x01(\tR\busername\x12\x18\n" +
	"\amailbox\x18\x11 \x01(\tR\amailbox\x124\n" +
	"\x16fetch_interval_seconds\x18\x12 \x01(\x05R\x14fetchIntervalSeconds\x12\x17\n" +
	"\aflow_id\x18\x13 \x01(\x03R\x06flowId\x129\n" +
	"\tauth_type\x18\x14 \x01(\x0e2\x1c.webitel.email.EmailAuthTypeR\bauthType\x12H\n" +
	"\x0eoauth_provider\x18\x15 \x01(\x0e2!.webitel.email.EmailOAuthProviderR\roauthProvider\x12&\n" +
	"\x0foauth_client_id\x18\x16 \x01(\tR\roauthClientId\x12'\n" +
	"\x0foauth_connected\x18\x17 \x01(\bR\x0eoauthConnected\x12N\n" +
	"\x10connection_state\x18\x18 \x01(\x0e2#.webitel.email.EmailConnectionStateR\x0fconnectionState\x12A\n" +
	"\x1dlast_successful_connection_at\x18\x19 \x01(\x03R\x1alastSuccessfulConnectionAt\x12)\n" +
	"\x10connection_error\x18\x1a \x01(\tR\x0fconnectionError\x12\x1d\n" +
	"\n" +
	"created_at\x18\x1e \x01(\x03R\tcreatedAt\x12.\n" +
	"\n" +
	"created_by\x18\x1f \x01(\v2\x0f.general.LookupR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18  \x01(\x03R\tupdatedAt\x12.\n" +
	"\n" +
	"updated_by\x18! \x01(\v2\x0f.general.LookupR\tupdatedBy\"\xee\x06\n" +
	"\x11InputEmailProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12#\n" +
	"\remail_address\x18\x04 \x01(\tR\femailAddress\x12\x1f\n" +
	"\vsender_name\x18\x05 \x01(\tR\n" +
	"senderName\x12\x19\n" +
	"\breply_to\x18\x06 \x01(\tR\areplyTo\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12\x1b\n" +
	"\timap_host\x18\b \x01(\tR\bimapHost\x12\x1b\n" +
	"\timap_port\x18\t \x01(\x05R\bimapPort\x12K\n" +
	"\rimap_security\x18\n" +
	" \x01(\x0e2&.webitel.email.EmailConnectionSecurityR\fimapSecurity\x12\x1b\n" +
	"\tsmtp_host\x18\v \x01(\tR\bsmtpHost\x12\x1b\n" +
	"\tsmtp_port\x18\f \x01(\x05R\bsmtpPort\x12K\n" +
	"\rsmtp_security\x18\r \x01(\x0e2&.webitel.email.EmailConnectionSecurityR\fsmtpSecurity\x12\x1a\n" +
	"\busername\x18\x0e \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x0f \x01(\tR\bpassword\x12\x18\n" +
	"\amailbox\x18\x10 \x01(\tR\amailbox\x124\n" +
	"\x16fetch_interval_seconds\x18\x11 \x01(\x05R\x14fetchIntervalSeconds\x12\x17\n" +
	"\aflow_id\x18\x12 \x01(\x03R\x06flowId\x129\n" +
	"\tauth_type\x18\x13 \x01(\x0e2\x1c.webitel.email.EmailAuthTypeR\bauthType\x12H\n" +
	"\x0eoauth_provider\x18\x14 \x01(\x0e2!.webitel.email.EmailOAuthProviderR\roauthProvider\x12&\n" +
	"\x0foauth_client_id\x18\x15 \x01(\tR\roauthClientId\x12.\n" +
	"\x13oauth_client_secret\x18\x16 \x01(\tR\x11oauthClientSecret\"|\n" +
	"\x18ListEmailProfilesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x16\n" +
	"\x06fields\x18\x05 \x03(\tR\x06fields\"Y\n" +
	"\x10EmailProfileList\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.webitel.email.EmailProfileR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\"+\n" +
	"\x19LocateEmailProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"S\n" +
	"\x19CreateEmailProfileRequest\x126\n" +
	"\x05input\x18\x01 \x01(\v2 .webitel.email.InputEmailProfileR\x05input\"c\n" +
	"\x19UpdateEmailProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x126\n" +
	"\x05input\x18\x02 \x01(\v2 .webitel.email.InputEmailProfileR\x05input\"+\n" +
	"\x19DeleteEmailProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\x17TestEmailProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x19EmailConnectionTestResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x96\x01\n" +
	"\x18TestEmailProfileResponse\x12<\n" +
	"\x04imap\x18\x01 \x01(\v2(.webitel.email.EmailConnectionTestResultR\x04imap\x12<\n" +
	"\x04smtp\x18\x02 \x01(\v2(.webitel.email.EmailConnectionTestResultR\x04smtp\"/\n" +
	"\x1dBeginEmailProfileOAuthRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Q\n" +
	"\x1eBeginEmailProfileOAuthResponse\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\\\n" +
	" CompleteEmailProfileOAuthRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"4\n" +
	"\"DisconnectEmailProfileOAuthRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id*g\n" +
	"\rEmailAuthType\x12\x1f\n" +
	"\x1bEMAIL_AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EMAIL_AUTH_TYPE_BASIC\x10\x01\x12\x1a\n" +
	"\x16EMAIL_AUTH_TYPE_OAUTH2\x10\x02*\x7f\n" +
	"\x12EmailOAuthProvider\x12$\n" +
	" EMAIL_OAUTH_PROVIDER_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bEMAIL_OAUTH_PROVIDER_GOOGLE\x10\x01\x12\"\n" +
	"\x1eEMAIL_OAUTH_PROVIDER_MICROSOFT\x10\x02*\x8f\x01\n" +
	"\x17EmailConnectionSecurity\x12)\n" +
	"%EMAIL_CONNECTION_SECURITY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dEMAIL_CONNECTION_SECURITY_TLS\x10\x01\x12&\n" +
	"\"EMAIL_CONNECTION_SECURITY_STARTTLS\x10\x02*\xd8\x01\n" +
	"\x14EmailConnectionState\x12&\n" +
	"\"EMAIL_CONNECTION_STATE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bEMAIL_CONNECTION_STATE_IDLE\x10\x01\x12 \n" +
	"\x1cEMAIL_CONNECTION_STATE_READY\x10\x02\x12 \n" +
	"\x1cEMAIL_CONNECTION_STATE_ERROR\x10\x03\x123\n" +
	"/EMAIL_CONNECTION_STATE_REAUTHORIZATION_REQUIRED\x10\x042\xcf\n" +
	"\n" +
	"\rEmailProfiles\x12}\n" +
	"\x11ListEmailProfiles\x12'.webitel.email.ListEmailProfilesRequest\x1a\x1f.webitel.email.EmailProfileList\"\x1e\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/email/profiles\x12\x80\x01\n" +
	"\x12LocateEmailProfile\x12(.webitel.email.LocateEmailProfileRequest\x1a\x1b.webitel.email.EmailProfile\"#\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/email/profiles/{id}\x12\x82\x01\n" +
	"\x12CreateEmailProfile\x12(.webitel.email.CreateEmailProfileRequest\x1a\x1b.webitel.email.EmailProfile\"%\x90\xb5\x18\x00\x82\xd3\xe4\x93\x02\x1b:\x05input\"\x12/v1/email/profiles\x12\xa9\x01\n" +
	"\x12UpdateEmailProfile\x12(.webitel.email.UpdateEmailProfileRequest\x1a\x1b.webitel.email.EmailProfile\"L\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02B:\x05inputZ :\x05input2\x17/v1/email/profiles/{id}\x1a\x17/v1/email/profiles/{id}\x12\x80\x01\n" +
	"\x12DeleteEmailProfile\x12(.webitel.email.DeleteEmailProfileRequest\x1a\x1b.webitel.email.EmailProfile\"#\x90\xb5\x18\x03\x82\xd3\xe4\x93\x02\x19*\x17/v1/email/profiles/{id}\x12\x8d\x01\n" +
	"\x10TestEmailProfile\x12&.webitel.email.TestEmailProfileRequest\x1a'.webitel.email.TestEmailProfileResponse\"(\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02\x1e\"\x1c/v1/email/profiles/{id}/test\x12\xa6\x01\n" +
	"\x16BeginEmailProfileOAuth\x12,.webitel.email.BeginEmailProfileOAuthRequest\x1a-.webitel.email.BeginEmailProfileOAuthResponse\"/\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02%\"#/v1/email/profiles/{id}/oauth/start\x12\xa0\x01\n" +
	"\x19CompleteEmailProfileOAuth\x12/.webitel.email.CompleteEmailProfileOAuthRequest\x1a\x1b.webitel.email.EmailProfile\"5\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/email/profiles/{id}/oauth/callback\x12\x98\x01\n" +
	"\x1bDisconnectEmailProfileOAuth\x121.webitel.email.DisconnectEmailProfileOAuthRequest\x1a\x1b.webitel.email.EmailProfile\")\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02\x1f*\x1d/v1/email/profiles/{id}/oauth\x1a\x11\x8a\xb5\x18\remail_profileB\xa9\x01\n" +
	"\x11com.webitel.emailB\fProfileProtoP\x01Z1github.com/webitel/webitel-emails/api/email;email\xa2\x02\x03WEX\xaa\x02\rWebitel.Email\xca\x02\rWebitel\\Email\xe2\x02\x19Webitel\\Email\\GPBMetadata\xea\x02\x0eWebitel::Emailb\x06proto3"

var (
	file_profile_proto_rawDescOnce sync.Once
	file_profile_proto_rawDescData []byte
)

func file_profile_proto_rawDescGZIP() []byte {
	file_profile_proto_rawDescOnce.Do(func() {
		file_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)))
	})
	return file_profile_proto_rawDescData
}

var file_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_profile_proto_goTypes = []any{
	(EmailAuthType)(0),                         // 0: webitel.email.EmailAuthType
	(EmailOAuthProvider)(0),                    // 1: webitel.email.EmailOAuthProvider
	(EmailConnectionSecurity)(0),               // 2: webitel.email.EmailConnectionSecurity
	(EmailConnectionState)(0),                  // 3: webitel.email.EmailConnectionState
	(*EmailProfile)(nil),                       // 4: webitel.email.EmailProfile
	(*InputEmailProfile)(nil),                  // 5: webitel.email.InputEmailProfile
	(*ListEmailProfilesRequest)(nil),           // 6: webitel.email.ListEmailProfilesRequest
	(*EmailProfileList)(nil),                   // 7: webitel.email.EmailProfileList
	(*LocateEmailProfileRequest)(nil),          // 8: webitel.email.LocateEmailProfileRequest
	(*CreateEmailProfileRequest)(nil),          // 9: webitel.email.CreateEmailProfileRequest
	(*UpdateEmailProfileRequest)(nil),          // 10: webitel.email.UpdateEmailProfileRequest
	(*DeleteEmailProfileRequest)(nil),          // 11: webitel.email.DeleteEmailProfileRequest
	(*TestEmailProfileRequest)(nil),            // 12: webitel.email.TestEmailProfileRequest
	(*EmailConnectionTestResult)(nil),          // 13: webitel.email.EmailConnectionTestResult
	(*TestEmailProfileResponse)(nil),           // 14: webitel.email.TestEmailProfileResponse
	(*BeginEmailProfileOAuthRequest)(nil),      // 15: webitel.email.BeginEmailProfileOAuthRequest
	(*BeginEmailProfileOAuthResponse)(nil),     // 16: webitel.email.BeginEmailProfileOAuthResponse
	(*CompleteEmailProfileOAuthRequest)(nil),   // 17: webitel.email.CompleteEmailProfileOAuthRequest
	(*DisconnectEmailProfileOAuthRequest)(nil), // 18: webitel.email.DisconnectEmailProfileOAuthRequest
	(*Lookup)(nil),                             // 19: general.Lookup
}
var file_profile_proto_depIdxs = []int32{
	2,  // 0: webitel.email.EmailProfile.imap_security:type_name -> webitel.email.EmailConnectionSecurity
	2,  // 1: webitel.email.EmailProfile.smtp_security:type_name -> webitel.email.EmailConnectionSecurity
	0,  // 2: webitel.email.EmailProfile.auth_type:type_name -> webitel.email.EmailAuthType
	1,  // 3: webitel.email.EmailProfile.oauth_provider:type_name -> webitel.email.EmailOAuthProvider
	3,  // 4: webitel.email.EmailProfile.connection_state:type_name -> webitel.email.EmailConnectionState
	19, // 5: webitel.email.EmailProfile.created_by:type_name -> general.Lookup
	19, // 6: webitel.email.EmailProfile.updated_by:type_name -> general.Lookup
	2,  // 7: webitel.email.InputEmailProfile.imap_security:type_name -> webitel.email.EmailConnectionSecurity
	2,  // 8: webitel.email.InputEmailProfile.smtp_security:type_name -> webitel.email.EmailConnectionSecurity
	0,  // 9: webitel.email.InputEmailProfile.auth_type:type_name -> webitel.email.EmailAuthType
	1,  // 10: webitel.email.InputEmailProfile.oauth_provider:type_name -> webitel.email.EmailOAuthProvider
	4,  // 11: webitel.email.EmailProfileList.items:type_name -> webitel.email.EmailProfile
	5,  // 12: webitel.email.CreateEmailProfileRequest.input:type_name -> webitel.email.InputEmailProfile
	5,  // 13: webitel.email.UpdateEmailProfileRequest.input:type_name -> webitel.email.InputEmailProfile
	13, // 14: webitel.email.TestEmailProfileResponse.imap:type_name -> webitel.email.EmailConnectionTestResult
	13, // 15: webitel.email.TestEmailProfileResponse.smtp:type_name -> webitel.email.EmailConnectionTestResult
	6,  // 16: webitel.email.EmailProfiles.ListEmailProfiles:input_type -> webitel.email.ListEmailProfilesRequest
	8,  // 17: webitel.email.EmailProfiles.LocateEmailProfile:input_type -> webitel.email.LocateEmailProfileRequest
	9,  // 18: webitel.email.EmailProfiles.CreateEmailProfile:input_type -> webitel.email.CreateEmailProfileRequest
	10, // 19: webitel.email.EmailProfiles.UpdateEmailProfile:input_type -> webitel.email.UpdateEmailProfileRequest
	11, // 20: webitel.email.EmailProfiles.DeleteEmailProfile:input_type -> webitel.email.DeleteEmailProfileRequest
	12, // 21: webitel.email.EmailProfiles.TestEmailProfile:input_type -> webitel.email.TestEmailProfileRequest
	15, // 22: webitel.email.EmailProfiles.BeginEmailProfileOAuth:input_type -> webitel.email.BeginEmailProfileOAuthRequest
	17, // 23: webitel.email.EmailProfiles.CompleteEmailProfileOAuth:input_type -> webitel.email.CompleteEmailProfileOAuthRequest
	18, // 24: webitel.email.EmailProfiles.DisconnectEmailProfileOAuth:input_type -> webitel.email.DisconnectEmailProfileOAuthRequest
	7,  // 25: webitel.email.EmailProfiles.ListEmailProfiles:output_type -> webitel.email.EmailProfileList
	4,  // 26: webitel.email.EmailProfiles.LocateEmailProfile:output_type -> webitel.email.EmailProfile
	4,  // 27: webitel.email.EmailProfiles.CreateEmailProfile:output_type -> webitel.email.EmailProfile
	4,  // 28: webitel.email.EmailProfiles.UpdateEmailProfile:output_type -> webitel.email.EmailProfile
	4,  // 29: webitel.email.EmailProfiles.DeleteEmailProfile:output_type -> webitel.email.EmailProfile
	14, // 30: webitel.email.EmailProfiles.TestEmailProfile:output_type -> webitel.email.TestEmailProfileResponse
	16, // 31: webitel.email.EmailProfiles.BeginEmailProfileOAuth:output_type -> webitel.email.BeginEmailProfileOAuthResponse
	4,  // 32: webitel.email.EmailProfiles.CompleteEmailProfileOAuth:output_type -> webitel.email.EmailProfile
	4,  // 33: webitel.email.EmailProfiles.DisconnectEmailProfileOAuth:output_type -> webitel.email.EmailProfile
	25, // [25:34] is the sub-list for method output_type
	16, // [16:25] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_profile_proto_init() }
func file_profile_proto_init() {
	if File_profile_proto != nil {
		return
	}
	file_general_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_proto_goTypes,
		DependencyIndexes: file_profile_proto_depIdxs,
		EnumInfos:         file_profile_proto_enumTypes,
		MessageInfos:      file_profile_proto_msgTypes,
	}.Build()
	File_profile_proto = out.File
	file_profile_proto_goTypes = nil
	file_profile_proto_depIdxs = nil
}
