// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: profile.proto

package email

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailProfiles_ListEmailProfiles_FullMethodName           = "/webitel.email.EmailProfiles/ListEmailProfiles"
	EmailProfiles_LocateEmailProfile_FullMethodName          = "/webitel.email.EmailProfiles/LocateEmailProfile"
	EmailProfiles_CreateEmailProfile_FullMethodName          = "/webitel.email.EmailProfiles/CreateEmailProfile"
	EmailProfiles_UpdateEmailProfile_FullMethodName          = "/webitel.email.EmailProfiles/UpdateEmailProfile"
	EmailProfiles_DeleteEmailProfile_FullMethodName          = "/webitel.email.EmailProfiles/DeleteEmailProfile"
	EmailProfiles_TestEmailProfile_FullMethodName            = "/webitel.email.EmailProfiles/TestEmailProfile"
	EmailProfiles_BeginEmailProfileOAuth_FullMethodName      = "/webitel.email.EmailProfiles/BeginEmailProfileOAuth"
	EmailProfiles_CompleteEmailProfileOAuth_FullMethodName   = "/webitel.email.EmailProfiles/CompleteEmailProfileOAuth"
	EmailProfiles_DisconnectEmailProfileOAuth_FullMethodName = "/webitel.email.EmailProfiles/DisconnectEmailProfileOAuth"
)

// EmailProfilesClient is the client API for EmailProfiles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmailProfiles manages mailbox connection settings and authorization.
type EmailProfilesClient interface {
	ListEmailProfiles(ctx context.Context, in *ListEmailProfilesRequest, opts ...grpc.CallOption) (*EmailProfileList, error)
	LocateEmailProfile(ctx context.Context, in *LocateEmailProfileRequest, opts ...grpc.CallOption) (*EmailProfile, error)
	CreateEmailProfile(ctx context.Context, in *CreateEmailProfileRequest, opts ...grpc.CallOption) (*EmailProfile, error)
	UpdateEmailProfile(ctx context.Context, in *UpdateEmailProfileRequest, opts ...grpc.CallOption) (*EmailProfile, error)
	DeleteEmailProfile(ctx context.Context, in *DeleteEmailProfileRequest, opts ...grpc.CallOption) (*EmailProfile, error)
	TestEmailProfile(ctx context.Context, in *TestEmailProfileRequest, opts ...grpc.CallOption) (*TestEmailProfileResponse, error)
	BeginEmailProfileOAuth(ctx context.Context, in *BeginEmailProfileOAuthRequest, opts ...grpc.CallOption) (*BeginEmailProfileOAuthResponse, error)
	CompleteEmailProfileOAuth(ctx context.Context, in *CompleteEmailProfileOAuthRequest, opts ...grpc.CallOption) (*EmailProfile, error)
	DisconnectEmailProfileOAuth(ctx context.Context, in *DisconnectEmailProfileOAuthRequest, opts ...grpc.CallOption) (*EmailProfile, error)
}

type emailProfilesClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailProfilesClient(cc grpc.ClientConnInterface) EmailProfilesClient {
	return &emailProfilesClient{cc}
}

func (c *emailProfilesClient) ListEmailProfiles(ctx context.Context, in *ListEmailProfilesRequest, opts ...grpc.CallOption) (*EmailProfileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailProfileList)
	err := c.cc.Invoke(ctx, EmailProfiles_ListEmailProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailProfilesClient) LocateEmailProfile(ctx context.Context, in *LocateEmailProfileRequest, opts ...grpc.CallOption) (*EmailProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailProfile)
	err := c.cc.Invoke(ctx, EmailProfiles_LocateEmailProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailProfilesClient) CreateEmailProfile(ctx context.Context, in *CreateEmailProfileRequest, opts ...grpc.CallOption) (*EmailProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailProfile)
	err := c.cc.Invoke(ctx, EmailProfiles_CreateEmailProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailProfilesClient) UpdateEmailProfile(ctx context.Context, in *UpdateEmailProfileRequest, opts ...grpc.CallOption) (*EmailProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailProfile)
	err := c.cc.Invoke(ctx, EmailProfiles_UpdateEmailProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailProfilesClient) DeleteEmailProfile(ctx context.Context, in *DeleteEmailProfileRequest, opts ...grpc.CallOption) (*EmailProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailProfile)
	err := c.cc.Invoke(ctx, EmailProfiles_DeleteEmailProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailProfilesClient) TestEmailProfile(ctx context.Context, in *TestEmailProfileRequest, opts ...grpc.CallOption) (*TestEmailProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestEmailProfileResponse)
	err := c.cc.Invoke(ctx, EmailProfiles_TestEmailProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailProfilesClient) BeginEmailProfileOAuth(ctx context.Context, in *BeginEmailProfileOAuthRequest, opts ...grpc.CallOption) (*BeginEmailProfileOAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginEmailProfileOAuthResponse)
	err := c.cc.Invoke(ctx, EmailProfiles_BeginEmailProfileOAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailProfilesClient) CompleteEmailProfileOAuth(ctx context.Context, in *CompleteEmailProfileOAuthRequest, opts ...grpc.CallOption) (*EmailProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailProfile)
	err := c.cc.Invoke(ctx, EmailProfiles_CompleteEmailProfileOAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailProfilesClient) DisconnectEmailProfileOAuth(ctx context.Context, in *DisconnectEmailProfileOAuthRequest, opts ...grpc.CallOption) (*EmailProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailProfile)
	err := c.cc.Invoke(ctx, EmailProfiles_DisconnectEmailProfileOAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailProfilesServer is the server API for EmailProfiles service.
// All implementations must embed UnimplementedEmailProfilesServer
// for forward compatibility.
//
// EmailProfiles manages mailbox connection settings and authorization.
type EmailProfilesServer interface {
	ListEmailProfiles(context.Context, *ListEmailProfilesRequest) (*EmailProfileList, error)
	LocateEmailProfile(context.Context, *LocateEmailProfileRequest) (*EmailProfile, error)
	CreateEmailProfile(context.Context, *CreateEmailProfileRequest) (*EmailProfile, error)
	UpdateEmailProfile(context.Context, *UpdateEmailProfileRequest) (*EmailProfile, error)
	DeleteEmailProfile(context.Context, *DeleteEmailProfileRequest) (*EmailProfile, error)
	TestEmailProfile(context.Context, *TestEmailProfileRequest) (*TestEmailProfileResponse, error)
	BeginEmailProfileOAuth(context.Context, *BeginEmailProfileOAuthRequest) (*BeginEmailProfileOAuthResponse, error)
	CompleteEmailProfileOAuth(context.Context, *CompleteEmailProfileOAuthRequest) (*EmailProfile, error)
	DisconnectEmailProfileOAuth(context.Context, *DisconnectEmailProfileOAuthRequest) (*EmailProfile, error)
	mustEmbedUnimplementedEmailProfilesServer()
}

// UnimplementedEmailProfilesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailProfilesServer struct{}

func (UnimplementedEmailProfilesServer) ListEmailProfiles(context.Context, *ListEmailProfilesRequest) (*EmailProfileList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEmailProfiles not implemented")
}
func (UnimplementedEmailProfilesServer) LocateEmailProfile(context.Context, *LocateEmailProfileRequest) (*EmailProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method LocateEmailProfile not implemented")
}
func (UnimplementedEmailProfilesServer) CreateEmailProfile(context.Context, *CreateEmailProfileRequest) (*EmailProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEmailProfile not implemented")
}
func (UnimplementedEmailProfilesServer) UpdateEmailProfile(context.Context, *UpdateEmailProfileRequest) (*EmailProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEmailProfile not implemented")
}
func (UnimplementedEmailProfilesServer) DeleteEmailProfile(context.Context, *DeleteEmailProfileRequest) (*EmailProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEmailProfile not implemented")
}
func (UnimplementedEmailProfilesServer) TestEmailProfile(context.Context, *TestEmailProfileRequest) (*TestEmailProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestEmailProfile not implemented")
}
func (UnimplementedEmailProfilesServer) BeginEmailProfileOAuth(context.Context, *BeginEmailProfileOAuthRequest) (*BeginEmailProfileOAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginEmailProfileOAuth not implemented")
}
func (UnimplementedEmailProfilesServer) CompleteEmailProfileOAuth(context.Context, *CompleteEmailProfileOAuthRequest) (*EmailProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteEmailProfileOAuth not implemented")
}
func (UnimplementedEmailProfilesServer) DisconnectEmailProfileOAuth(context.Context, *DisconnectEmailProfileOAuthRequest) (*EmailProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectEmailProfileOAuth not implemented")
}
func (UnimplementedEmailProfilesServer) mustEmbedUnimplementedEmailProfilesServer() {}
func (UnimplementedEmailProfilesServer) testEmbeddedByValue()                       {}

// UnsafeEmailProfilesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailProfilesServer will
// result in compilation errors.
type UnsafeEmailProfilesServer interface {
	mustEmbedUnimplementedEmailProfilesServer()
}

func RegisterEmailProfilesServer(s grpc.ServiceRegistrar, srv EmailProfilesServer) {
	// If the following call panics, it indicates UnimplementedEmailProfilesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailProfiles_ServiceDesc, srv)
}

func _EmailProfiles_ListEmailProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEmailProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailProfilesServer).ListEmailProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailProfiles_ListEmailProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailProfilesServer).ListEmailProfiles(ctx, req.(*ListEmailProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailProfiles_LocateEmailProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateEmailProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailProfilesServer).LocateEmailProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailProfiles_LocateEmailProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailProfilesServer).LocateEmailProfile(ctx, req.(*LocateEmailProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailProfiles_CreateEmailProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmailProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailProfilesServer).CreateEmailProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailProfiles_CreateEmailProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailProfilesServer).CreateEmailProfile(ctx, req.(*CreateEmailProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailProfiles_UpdateEmailProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmailProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailProfilesServer).UpdateEmailProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailProfiles_UpdateEmailProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailProfilesServer).UpdateEmailProfile(ctx, req.(*UpdateEmailProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailProfiles_DeleteEmailProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmailProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailProfilesServer).DeleteEmailProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailProfiles_DeleteEmailProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailProfilesServer).DeleteEmailProfile(ctx, req.(*DeleteEmailProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailProfiles_TestEmailProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestEmailProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailProfilesServer).TestEmailProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailProfiles_TestEmailProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailProfilesServer).TestEmailProfile(ctx, req.(*TestEmailProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailProfiles_BeginEmailProfileOAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginEmailProfileOAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailProfilesServer).BeginEmailProfileOAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailProfiles_BeginEmailProfileOAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailProfilesServer).BeginEmailProfileOAuth(ctx, req.(*BeginEmailProfileOAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailProfiles_CompleteEmailProfileOAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteEmailProfileOAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailProfilesServer).CompleteEmailProfileOAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailProfiles_CompleteEmailProfileOAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailProfilesServer).CompleteEmailProfileOAuth(ctx, req.(*CompleteEmailProfileOAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailProfiles_DisconnectEmailProfileOAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectEmailProfileOAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailProfilesServer).DisconnectEmailProfileOAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailProfiles_DisconnectEmailProfileOAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailProfilesServer).DisconnectEmailProfileOAuth(ctx, req.(*DisconnectEmailProfileOAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailProfiles_ServiceDesc is the grpc.ServiceDesc for EmailProfiles service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailProfiles_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webitel.email.EmailProfiles",
	HandlerType: (*EmailProfilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEmailProfiles",
			Handler:    _EmailProfiles_ListEmailProfiles_Handler,
		},
		{
			MethodName: "LocateEmailProfile",
			Handler:    _EmailProfiles_LocateEmailProfile_Handler,
		},
		{
			MethodName: "CreateEmailProfile",
			Handler:    _EmailProfiles_CreateEmailProfile_Handler,
		},
		{
			MethodName: "UpdateEmailProfile",
			Handler:    _EmailProfiles_UpdateEmailProfile_Handler,
		},
		{
			MethodName: "DeleteEmailProfile",
			Handler:    _EmailProfiles_DeleteEmailProfile_Handler,
		},
		{
			MethodName: "TestEmailProfile",
			Handler:    _EmailProfiles_TestEmailProfile_Handler,
		},
		{
			MethodName: "BeginEmailProfileOAuth",
			Handler:    _EmailProfiles_BeginEmailProfileOAuth_Handler,
		},
		{
			MethodName: "CompleteEmailProfileOAuth",
			Handler:    _EmailProfiles_CompleteEmailProfileOAuth_Handler,
		},
		{
			MethodName: "DisconnectEmailProfileOAuth",
			Handler:    _EmailProfiles_DisconnectEmailProfileOAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}
