// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: thread.proto

package email

import (
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BindEmailThreadContactRequest selects a conversation and the contact to link.
type BindEmailThreadContactRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ThreadId int64                  `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	// Identifier of an existing contact of the same domain.
	ContactId     int64 `protobuf:"varint,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindEmailThreadContactRequest) Reset() {
	*x = BindEmailThreadContactRequest{}
	mi := &file_thread_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindEmailThreadContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEmailThreadContactRequest) ProtoMessage() {}

func (x *BindEmailThreadContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEmailThreadContactRequest.ProtoReflect.Descriptor instead.
func (*BindEmailThreadContactRequest) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{0}
}

func (x *BindEmailThreadContactRequest) GetThreadId() int64 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *BindEmailThreadContactRequest) GetContactId() int64 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

// BindEmailThreadContactResponse confirms the binding.
type BindEmailThreadContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindEmailThreadContactResponse) Reset() {
	*x = BindEmailThreadContactResponse{}
	mi := &file_thread_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindEmailThreadContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEmailThreadContactResponse) ProtoMessage() {}

func (x *BindEmailThreadContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEmailThreadContactResponse.ProtoReflect.Descriptor instead.
func (*BindEmailThreadContactResponse) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{1}
}

// UnbindEmailThreadContactRequest selects the conversation to unlink.
type UnbindEmailThreadContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      int64                  `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindEmailThreadContactRequest) Reset() {
	*x = UnbindEmailThreadContactRequest{}
	mi := &file_thread_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindEmailThreadContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindEmailThreadContactRequest) ProtoMessage() {}

func (x *UnbindEmailThreadContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindEmailThreadContactRequest.ProtoReflect.Descriptor instead.
func (*UnbindEmailThreadContactRequest) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{2}
}

func (x *UnbindEmailThreadContactRequest) GetThreadId() int64 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

// UnbindEmailThreadContactResponse confirms the removal.
type UnbindEmailThreadContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindEmailThreadContactResponse) Reset() {
	*x = UnbindEmailThreadContactResponse{}
	mi := &file_thread_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindEmailThreadContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindEmailThreadContactResponse) ProtoMessage() {}

func (x *UnbindEmailThreadContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindEmailThreadContactResponse.ProtoReflect.Descriptor instead.
func (*UnbindEmailThreadContactResponse) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{3}
}

var File_thread_proto protoreflect.FileDescriptor

const file_thread_proto_rawDesc = "" +
	"\n" +
	"\fthread.proto\x12\rwebitel.email\x1a\x1cgoogle/api/annotations.proto\x1a\x1aproto/webitel/option.proto\"[\n" +
	"\x1dBindEmailThreadContactRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\x03R\bthreadId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\x03R\tcontactId\" \n" +
	"\x1eBindEmailThreadContactResponse\">\n" +
	"\x1fUnbindEmailThreadContactRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\x03R\bthreadId\"\"\n" +
	" UnbindEmailThreadContactResponse2\xff\x02\n" +
	"\fEmailThreads\x12\xab\x01\n" +
	"\x16BindEmailThreadContact\x12,.webitel.email.BindEmailThreadContactRequest\x1a-.webitel.email.BindEmailThreadContactResponse\"4\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02*:\x01*\x1a%/v1/email/threads/{thread_id}/contact\x12\xae\x01\n" +
	"\x18UnbindEmailThreadContact\x12..webitel.email.UnbindEmailThreadContactRequest\x1a/.webitel.email.UnbindEmailThreadContactResponse\"1\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02'*%/v1/email/threads/{thread_id}/contact\x1a\x10\x8a\xb5\x18\femail_threadB\xa8\x01\n" +
	"\x11com.webitel.emailB\vThreadProtoP\x01Z1github.com/webitel/webitel-emails/api/email;email\xa2\x02\x03WEX\xaa\x02\rWebitel.Email\xca\x02\rWebitel\\Email\xe2\x02\x19Webitel\\Email\\GPBMetadata\xea\x02\x0eWebitel::Emailb\x06proto3"

var (
	file_thread_proto_rawDescOnce sync.Once
	file_thread_proto_rawDescData []byte
)

func file_thread_proto_rawDescGZIP() []byte {
	file_thread_proto_rawDescOnce.Do(func() {
		file_thread_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thread_proto_rawDesc), len(file_thread_proto_rawDesc)))
	})
	return file_thread_proto_rawDescData
}

var file_thread_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_thread_proto_goTypes = []any{
	(*BindEmailThreadContactRequest)(nil),    // 0: webitel.email.BindEmailThreadContactRequest
	(*BindEmailThreadContactResponse)(nil),   // 1: webitel.email.BindEmailThreadContactResponse
	(*UnbindEmailThreadContactRequest)(nil),  // 2: webitel.email.UnbindEmailThreadContactRequest
	(*UnbindEmailThreadContactResponse)(nil), // 3: webitel.email.UnbindEmailThreadContactResponse
}
var file_thread_proto_depIdxs = []int32{
	0, // 0: webitel.email.EmailThreads.BindEmailThreadContact:input_type -> webitel.email.BindEmailThreadContactRequest
	2, // 1: webitel.email.EmailThreads.UnbindEmailThreadContact:input_type -> webitel.email.UnbindEmailThreadContactRequest
	1, // 2: webitel.email.EmailThreads.BindEmailThreadContact:output_type -> webitel.email.BindEmailThreadContactResponse
	3, // 3: webitel.email.EmailThreads.UnbindEmailThreadContact:output_type -> webitel.email.UnbindEmailThreadContactResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_thread_proto_init() }
func file_thread_proto_init() {
	if File_thread_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thread_proto_rawDesc), len(file_thread_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thread_proto_goTypes,
		DependencyIndexes: file_thread_proto_depIdxs,
		MessageInfos:      file_thread_proto_msgTypes,
	}.Build()
	File_thread_proto = out.File
	file_thread_proto_goTypes = nil
	file_thread_proto_depIdxs = nil
}
