// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: thread.proto

package email

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailThreads_BindEmailThreadContact_FullMethodName   = "/webitel.email.EmailThreads/BindEmailThreadContact"
	EmailThreads_UnbindEmailThreadContact_FullMethodName = "/webitel.email.EmailThreads/UnbindEmailThreadContact"
)

// EmailThreadsClient is the client API for EmailThreads service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmailThreads serves the operator decisions about an email conversation.
type EmailThreadsClient interface {
	// BindEmailThreadContact links a conversation to a contact chosen by an
	// operator. It outranks automatic contact resolution, including a later one.
	// The contact itself is created in Contacts, under the operator's own session.
	BindEmailThreadContact(ctx context.Context, in *BindEmailThreadContactRequest, opts ...grpc.CallOption) (*BindEmailThreadContactResponse, error)
	// UnbindEmailThreadContact removes the contact of a conversation and keeps it
	// that way: automatic resolution never writes over an unlinked conversation.
	UnbindEmailThreadContact(ctx context.Context, in *UnbindEmailThreadContactRequest, opts ...grpc.CallOption) (*UnbindEmailThreadContactResponse, error)
}

type emailThreadsClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailThreadsClient(cc grpc.ClientConnInterface) EmailThreadsClient {
	return &emailThreadsClient{cc}
}

func (c *emailThreadsClient) BindEmailThreadContact(ctx context.Context, in *BindEmailThreadContactRequest, opts ...grpc.CallOption) (*BindEmailThreadContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindEmailThreadContactResponse)
	err := c.cc.Invoke(ctx, EmailThreads_BindEmailThreadContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailThreadsClient) UnbindEmailThreadContact(ctx context.Context, in *UnbindEmailThreadContactRequest, opts ...grpc.CallOption) (*UnbindEmailThreadContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbindEmailThreadContactResponse)
	err := c.cc.Invoke(ctx, EmailThreads_UnbindEmailThreadContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailThreadsServer is the server API for EmailThreads service.
// All implementations must embed UnimplementedEmailThreadsServer
// for forward compatibility.
//
// EmailThreads serves the operator decisions about an email conversation.
type EmailThreadsServer interface {
	// BindEmailThreadContact links a conversation to a contact chosen by an
	// operator. It outranks automatic contact resolution, including a later one.
	// The contact itself is created in Contacts, under the operator's own session.
	BindEmailThreadContact(context.Context, *BindEmailThreadContactRequest) (*BindEmailThreadContactResponse, error)
	// UnbindEmailThreadContact removes the contact of a conversation and keeps it
	// that way: automatic resolution never writes over an unlinked conversation.
	UnbindEmailThreadContact(context.Context, *UnbindEmailThreadContactRequest) (*UnbindEmailThreadContactResponse, error)
	mustEmbedUnimplementedEmailThreadsServer()
}

// UnimplementedEmailThreadsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailThreadsServer struct{}

func (UnimplementedEmailThreadsServer) BindEmailThreadContact(context.Context, *BindEmailThreadContactRequest) (*BindEmailThreadContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindEmailThreadContact not implemented")
}
func (UnimplementedEmailThreadsServer) UnbindEmailThreadContact(context.Context, *UnbindEmailThreadContactRequest) (*UnbindEmailThreadContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindEmailThreadContact not implemented")
}
func (UnimplementedEmailThreadsServer) mustEmbedUnimplementedEmailThreadsServer() {}
func (UnimplementedEmailThreadsServer) testEmbeddedByValue()                      {}

// UnsafeEmailThreadsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailThreadsServer will
// result in compilation errors.
type UnsafeEmailThreadsServer interface {
	mustEmbedUnimplementedEmailThreadsServer()
}

func RegisterEmailThreadsServer(s grpc.ServiceRegistrar, srv EmailThreadsServer) {
	// If the following call panics, it indicates UnimplementedEmailThreadsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailThreads_ServiceDesc, srv)
}

func _EmailThreads_BindEmailThreadContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindEmailThreadContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailThreadsServer).BindEmailThreadContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailThreads_BindEmailThreadContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailThreadsServer).BindEmailThreadContact(ctx, req.(*BindEmailThreadContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailThreads_UnbindEmailThreadContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindEmailThreadContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailThreadsServer).UnbindEmailThreadContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailThreads_UnbindEmailThreadContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailThreadsServer).UnbindEmailThreadContact(ctx, req.(*UnbindEmailThreadContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailThreads_ServiceDesc is the grpc.ServiceDesc for EmailThreads service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailThreads_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webitel.email.EmailThreads",
	HandlerType: (*EmailThreadsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BindEmailThreadContact",
			Handler:    _EmailThreads_BindEmailThreadContact_Handler,
		},
		{
			MethodName: "UnbindEmailThreadContact",
			Handler:    _EmailThreads_UnbindEmailThreadContact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thread.proto",
}
